### ISSUE TITLE
Release error with message:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Anduin2017** [marceloavf/github-tools-vsts#39]
## My configuration

```yaml
steps:
steps:
- task: marcelo-formentao.github-tools.github-release-publish-task.GitHubReleasePublish@1
  displayName: 'Create or Modify GitHub Release'
  inputs:
    githubEndpoint: GitHub
    githubRepository: AiursoftWeb/Kahla.CLI
    githubReleaseNotes: 'Pre release'
    githubReleaseDraft: false
    githubReleasePrerelease: true
    githubReleaseAsset: 'CLI/WindowsCLI/Kahla-CLI-Windows.zip'
    manifestJson: '$(System.DefaultWorkingDirectory)/CLI/WindowsCLI/package.json'
    githubReuseDraftOnly: false
    githubEditRelease: true
```

I have already made sure that the files are valid.

## Behavior

```log
2019-05-26T11:58:37.6128211Z ##[section]Starting: Create or Modify GitHub Release
2019-05-26T11:58:37.6236348Z ==============================================================================
2019-05-26T11:58:37.6236478Z Task         : Create or Modify GitHub Release
2019-05-26T11:58:37.6236569Z Description  : Create or modify GitHub Release, allowing to upload assets, check manifest content and more.
2019-05-26T11:58:37.6236661Z Version      : 1.0.0
2019-05-26T11:58:37.6236746Z Author       : Marcelo Formentão
2019-05-26T11:58:37.6236846Z Help         : [More Information](https://github.com/marceloavf/github-tools-vsts) (Version 1.0.0).
2019-05-26T11:58:37.6236933Z ==============================================================================
2019-05-26T11:58:38.0790147Z bf6e942d-3c1c-4d29-b267-9d3b3e543ea3 exists true
2019-05-26T11:58:38.2138257Z D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1
2019-05-26T11:58:38.2138968Z (function (exports, require, module, __filename, __dirname) { module.exports=function(e){var t={};function a(i){if(t[i])return t[i].exports;var r=t[i]={i:i,l:!1,exports:{}};return e[i].call(r.exports,r,r.exports,a),r.l=!0,r.exports}return a.m=e,a.c=t,a.d=function(e,t,i){a.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:i})},a.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(t,"a",t),t},a.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},a.p="",a(a.s=106)}([function(e,t){e.exports=require("fs")},function(e,t,a){var i=a(25),r=a(12).Stream,n=a(2),o=/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/;function s(e){return e.charAt(0).toUpperCase()+e.slice(1)}function c(e,t,a,r,o){throw new i.AssertionError({message:n.format("%s (%s) is required",e,t),actual:void 0===o?typeof r:o(r),expected:t,operator
2019-05-26T11:58:38.2140322Z 
2019-05-26T11:58:38.2140590Z RangeError: Maximum call stack size exceeded
2019-05-26T11:58:38.2140802Z     at Object.resolve (path.js:158:28)
2019-05-26T11:58:38.2141021Z     at Object._makeLong (path.js:664:32)
2019-05-26T11:58:38.2141618Z     at Object.fs.statSync (fs.js:1000:27)
2019-05-26T11:58:38.2141873Z     at z (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:371108)
2019-05-26T11:58:38.2142102Z     at k (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:369678)
2019-05-26T11:58:38.2142359Z     at w (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:370293)
2019-05-26T11:58:38.2142578Z     at k (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:370162)
2019-05-26T11:58:38.2142813Z     at w (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:370293)
2019-05-26T11:58:38.2143030Z     at k (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:370162)
2019-05-26T11:58:38.2143276Z     at w (D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js:1:370293)
2019-05-26T11:58:38.2441818Z ##[error]Exit code 7 returned from process: file name 'C:\agents\2.150.3\externals\node\bin\node.exe', arguments '"D:\a\_tasks\GitHubReleasePublish_0e54b1de-2c34-4acd-b93d-0fa1b9730bbe\1.0.0\githubReleasePublish.js"'.
2019-05-26T11:58:38.2458930Z ##[section]Finishing: Create or Modify GitHub Release
```

## Excepted

I hope my release could be success.

## Other info

What is the reason? Is it because of my configuration?

**Comment by marceloavf** [comment]
Hi @Anduin2017 

Thank you for this report, 
Could I know the size of the file you are trying to send?

**Comment by Anduin2017** [comment]
8 MB.

**Comment by marceloavf** [comment]
I'm investigating if there is some connection with the node version running the task.

Could you check the current node version running this task?
Are you using hosted machine or private one?

Thank you.

**Comment by Anduin2017** [comment]
Hi,

I am not using a private one. I have tried hosted Ubuntu, Windows container, Hosted Visual Studio. They all comes to the same issue.

**Comment by Anduin2017** [comment]
And, also. Our pipeline is public. Please see it here:

https://aiursoft.visualstudio.com/Star/_release?view=mine&definitionId=9

**Comment by marceloavf** [comment]
Thanks!

I saw that it happened sporadically, have you guys done something different with those newest release or it just started working again?

**Comment by Anduin2017** [comment]
We struggled for two days and had no result. So we deleted all jobs in this pipeline and tried to recreate the entire pipeline. 

And it works. Hard to find what impacts. Sorry about that.

**Comment by marceloavf** [comment]
It's being complicated to replicate the problem, so since this was resolved by your part I'll close this issue, but feel free to reopen it if it happens again.

Thank you!
