### ISSUE TITLE
Im running into an error

### ISSUE THREAD

**Issue by Logieee** [marceloavf/github-tools-vsts#75]
Im deploying a node js application into kubernettes container and getting this below error message:

node:fs:744
20
  handleErrorFromBinding(ctx);
19
  ^
18
17
Error: EISDIR: illegal operation on a directory, read
16
    at Object.readSync (node:fs:744:3)
15
    at tryReadSync (node:fs:439:20)
14
    at Object.readFileSync (node:fs:485:19)
13
    at transform (/app-root/node_modules/mongodb/lib/connection_string.js:916:23)
12
    at setOption (/app-root/node_modules/mongodb/lib/connection_string.js:443:36)
11
    at parseOptions (/app-root/node_modules/mongodb/lib/connection_string.js:289:9)
10
    at new MongoClient (/app-root/node_modules/mongodb/lib/mongo_client.js:45:63)
9
    at Object.connect (/app-root/helpers/connectDb.js:7:12)
8
    at Object.<anonymous> (/app-root/index.js:14:8)
7
    at Module._compile (node:internal/modules/cjs/loader:1205:14) {
6
  errno: -21,
5
  syscall: 'read',
4
  code: 'EISDIR'
3
}
2
1
Node.js v19.1.0

**Comment by marceloavf** [comment]
Hi @Logieee 

This seems not to be related with this task, but a problem with mongodb lib trying to read something in a folder it's not allowed.

**Comment by Logieee** [comment]
> Hi @Logieee
> 
> This seems not to be related with this task, but a problem with mongodb lib trying to read something in a folder it's not allowed.

Hi @marceloavf yes, you are right. Accidentally created an issue with this task. 

I have fixed the issue. I'll close this this now.
